### ISSUE TITLE
新しいBookを追加するときの検索ボックスを空欄でSearchするとNoMethodError in Books#searchになる

### ISSUE THREAD

**Issue by yumetodo** [Strawhub/Reading-Management#3]
## Fatal log

```
 Showing /home/yumetodo/Reading-Management/app/views/books/search.html.erb where line #7 raised:

undefined method `each' for nil:NilClass

     @result['items'].each do |item| 
                     ^^^^^

app/views/books/search.html.erb:7
app/controllers/books_controller.rb:50:in `search' 
```

# Step to reproduce

1. `/books`を開く
2. `Add New`ボタンを押す
3. 検索ボックスに何も打たずに`Search`を押す

**Comment by Strawhub** [comment]
issueを立てていただきありがとうございます。
検索フォームがブランクの状態で`Search`を押すとエラーが出る問題を以下のように修正しました。
1. フォームがブランクのままで検索リクエストを送信しないように修正。
2. 検索フォームがブランクの状態で'Search'を押すとalertを表示するように修正。

私自身だけでは気づかなかった問題に気づいていただきありがとうございます！

**Comment by yumetodo** [comment]
修正確認しました。
